# Generated by Django 2.1.1 on 2018-11-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('publishing_house', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('cover', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt.Assortment')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt.Assortment')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('tel_number', models.CharField(max_length=250)),
                ('loyalty_card', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('was_paid', models.BooleanField(default=True)),
                ('cash_on_delivery', models.BooleanField(default=True)),
                ('was_ordered', models.BooleanField(default=True)),
                ('total_amount', models.FloatField()),
                ('completed_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt.CompletedCart')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('tel_number', models.CharField(max_length=250)),
                ('salary', models.IntegerField()),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Projekt.JobTitle')),
            ],
        ),
        migrations.AddField(
            model_name='completedcart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt.Customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt.Customer'),
        ),
        migrations.AddField(
            model_name='assortment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt.Books'),
        ),
    ]
