# Generated by Django 2.1.2 on 2018-11-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projekt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.CharField(max_length=250),
        ),
    ]
