# Generated by Django 2.1.2 on 2018-11-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projekt', '0002_auto_20181101_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortment',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
