# Generated by Django 2.1.2 on 2018-11-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projekt', '0003_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedcart',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='completedcart',
            name='customer',
            field=models.CharField(max_length=250),
        ),
    ]
