# Generated by Django 2.1.2 on 2018-11-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projekt', '0003_assortment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
