# Generated by Django 2.1.2 on 2018-11-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projekt', '0004_auto_20181127_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedcart',
            name='the_same_id',
            field=models.IntegerField(default=0),
        ),
    ]
