# Generated by Django 2.1.2 on 2018-11-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projekt', '0005_auto_20181101_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
