# Generated by Django 2.1.2 on 2018-11-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projekt', '0006_books_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assortment',
            old_name='ISBN_CODE',
            new_name='book',
        ),
    ]
